export default [
  { name: "Regular User", email: "user@trello.com", password: "Password1!" },
  { name: "Admin User", email: "admin@trello.com", password: "Password1!", role: "ADMIN" },
  { name: "Freddie Mercury", email: "freddie@queen.com", password: "QueenR0cks!" },
  { name: "Brian May", email: "brian@queen.com", password: "RedSpecial#1" },
  { name: "Roger Taylor", email: "roger@queen.com", password: "DrumKing!9" },
  { name: "John Deacon", email: "john@queen.com", password: "Bassline$42" },
  { name: "Mick Jagger", email: "mick@rollingstones.com", password: "St0nes!2025" },
  { name: "Keith Richards", email: "keith@rollingstones.com", password: "Keef#Guitar7" },
  { name: "Charlie Watts", email: "charlie@rollingstones.com", password: "JazzDrum$8" },
  { name: "Ronnie Wood", email: "ronnie@rollingstones.com", password: "Faces*1975" },
  { name: "Robert Plant", email: "robert@ledzeppelin.com", password: "Zep$IV1971" },
  { name: "Jimmy Page", email: "jimmy@ledzeppelin.com", password: "DragonSuiT#9" },
  { name: "John Paul Jones", email: "johnpaul@ledzeppelin.com", password: "Multi1nstr!" },
  { name: "John Bonham", email: "bonzo@ledzeppelin.com", password: "MobyDick*77" },
  { name: "David Gilmour", email: "david@pinkfloyd.com", password: "Floydian$Slip1" },
  { name: "Roger Waters", email: "roger@pinkfloyd.com", password: "Wall#1979!" },
  { name: "Syd Barrett", email: "syd@pinkfloyd.com", password: "Piper@Dawn1" },
  { name: "Nick Mason", email: "nick@pinkfloyd.com", password: "Drum$Machine2" },
  { name: "Paul McCartney", email: "paul@thebeatles.com", password: "Beatle$64!" },
  { name: "John Lennon", email: "john@thebeatles.com", password: "Imagine#9!" },
  { name: "George Harrison", email: "george@thebeatles.com", password: "HereC0mes$un" },
  { name: "Ringo Starr", email: "ringo@thebeatles.com", password: "Octopus*8!" },
];
